repos:
  # Go hooks
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-fmt
        args: [-w]
      - id: go-imports
        args: [-w]
      - id: go-vet-mod
      - id: go-mod-tidy
      - id: golangci-lint-mod
        args: [--config=backend/.golangci.yml]

  # Frontend hooks
  - repo: local
    hooks:
      - id: eslint
        name: ESLint
        entry: bash -c 'cd frontend && npm run lint'
        language: system
        files: \.(ts|tsx|js|jsx)$
        pass_filenames: false

      - id: prettier
        name: Prettier
        entry: bash -c 'cd frontend && npm run format'
        language: system
        files: \.(ts|tsx|js|jsx|json|css|md)$
        pass_filenames: false

  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
        args: [--unsafe]
      - id: check-toml
      - id: check-xml
      - id: mixed-line-ending
        args: [--fix=lf]

  # Docker hooks
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        files: Dockerfile

  # Security hooks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: [--baseline, .secrets.baseline]
        exclude: package.lock.json

  # Commit message hooks
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.5.3
    hooks:
      - id: commitizen
        stages: [commit-msg]